import { PageShell } from '../components';
const items=[
['Facing Foreclosure','We begin by understanding the cause of foreclosure, balance owed, payment history, the current hardship, and your goals. We explore creative paths to rebuild credit, return the loan to good standing when possible, support continued occupancy, or prepare for a sale.','We are not looking for a one-size-fits-all solution or simply trying to buy a distressed property. We are focused on identifying the right solution for each homeowner.'],
['Unable to Sell or Need to Move Quickly','We can offer quick-sale and closing solutions, as well as alternative and creative options to selling when appropriate.','Every situation is different, and our recommendations are built around the homeowner rather than around a preset transaction.'],
['Seniors Who Want to Remain at Home','We meet with senior homeowners to understand their priorities and design a creative scenario that may help unlock financial resources while reducing the burdens that make aging in place difficult.','We focus on stability, dignity, quality of life, and helping seniors make the most of resources they worked hard to build.'],
['Seniors Ready to Downsize','For seniors who want to move but cannot or do not want to qualify for a traditional mortgage, we can help identify a suitable home and create a long-term occupancy arrangement designed around security and independence.','We seek to provide a true sense of home, long-term stability, and freedom from the maintenance burden of ownership.'],
['Buyers Outside Traditional Mortgage Guidelines','We evaluate employment, payment ability, and overall circumstances to identify a responsible price range, then help buyers find and secure a home they can work toward purchasing over time.','Our goal is not simply to get someone into a house. We want to create a healthy, responsible path to lasting homeownership.'],
['Veteran Homebuyers','VA property-condition rules can limit access to homes that need repairs. Ezra can partner with qualified veteran buyers to secure a property and create a path for needed work before a VA-financed purchase.','We honor veterans and want to help them overcome barriers while using the benefit they earned for the home they truly want.']];
export default function Help(){return <PageShell><main><section className="page-hero"><p className="eyebrow">HOW WE HELP</p><h1>When Life Changes, We're Here.</h1><p>We listen first, understand the whole situation, and create solutions that help people move forward.</p></section><section className="section"><div className="solution-list">{items.map(([t,a,d],i)=><article key={t}><span>{String(i+1).padStart(2,'0')}</span><div><h2>{t}</h2><h4>How Ezra Helps</h4><p>{a}</p><h4>What Makes Our Approach Different</h4><p>{d}</p></div></article>)}</div></section></main></PageShell>}
